# 展示隐藏文件
[mgr]
show_hidden = true
[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim" }
]

[open]
rules = [
    { name = "*.txt", use = "edit" },
    { name = "*.lua", use = "edit" },
    { name = "*.py",  use = "edit" },
    { name = "*.md",  use = "edit" },
    { mime = "text/*", use = "edit" },
]
